package com.example.journalapp.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

class Spacing(
    val none: Dp = 0.dp,
    val xxxSmall: Dp = 1.dp,
    val xxSmall: Dp = 2.dp,
    val xSmall: Dp = 4.dp,
    val small: Dp = 8.dp,
    val medium: Dp = 12.dp,
    val xMedium: Dp = 14.dp,
    val large: Dp = 16.dp,
    val xLarge: Dp = 20.dp,
    val xxLarge: Dp = 24.dp,
    val xxLarge2: Dp = 28.dp,
    val xxLarge3: Dp = 32.dp,
    val xxLarge4: Dp = 36.dp,
    val xxLarge5: Dp = 40.dp,
    val xxLarge6: Dp = 46.dp,
    val xxLarge7: Dp = 56.dp,
    val xxLarge8: Dp = 64.dp,
    val xxLarge9: Dp = 72.dp,
    val xxLarge10: Dp = 80.dp,
    val xxLarge11: Dp = 88.dp,
    val xxLarge12: Dp = 96.dp,
    val xxLarge13: Dp = 104.dp,
    val xxLarge14: Dp = 112.dp,
    val xxLarge15: Dp = 120.dp,
    val xxLarge16: Dp = 128.dp,
    val xxLarge17: Dp = 136.dp,
    val xxLarge18: Dp = 144.dp,
    val xxLarge19: Dp = 152.dp,
    val xxLarge20: Dp = 160.dp,
    val xxLarge21: Dp = 168.dp,
    val xxLarge22: Dp = 176.dp,
    val xxLarge23: Dp = 184.dp,
    val xxLarge24: Dp = 192.dp,
    val xxLarge25: Dp = 200.dp,
    val minTouchTargetSize: Dp = 48.dp,
)
